name: shop_list_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_speed_dial: ^7.0.0
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5
  google_fonts: ^6.2.1
  modal_progress_hud_nsn: ^0.5.0
  carousel_slider: ^5.0.0
  table_calendar: ^3.0.9

  fl_chart: ^0.64.0

  flutter_local_notifications: ^16.3.2

  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0

#  google_maps_flutter: ^2.5.0
#  geolocator: ^11.0.0
##  google_maps_webservice: ^0.0.19
#  flutter_polyline_points: ^2.0.0
#  provider: ^6.1.5
#
#  flutter_map: ^6.1.0
#  latlong2: ^0.9.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/


