// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDORoHNqwllIrLwR4EBsa7AQtf2aEe4QLQ',
    appId: '1:637551684753:web:84899d56f6ed60da722330',
    messagingSenderId: '637551684753',
    projectId: 'shoplistapp-6faad',
    authDomain: 'shoplistapp-6faad.firebaseapp.com',
    storageBucket: 'shoplistapp-6faad.firebasestorage.app',
    measurementId: 'G-FVYHRFE6Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF4LCfG0GQc5371Es8RyEkcOkYdNtohpM',
    appId: '1:637551684753:android:01c788ddebb9880b722330',
    messagingSenderId: '637551684753',
    projectId: 'shoplistapp-6faad',
    storageBucket: 'shoplistapp-6faad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHPlil8BnNdxvqY845jPq1KWGrcxAdZrU',
    appId: '1:637551684753:ios:98c24bec247b62a8722330',
    messagingSenderId: '637551684753',
    projectId: 'shoplistapp-6faad',
    storageBucket: 'shoplistapp-6faad.firebasestorage.app',
    iosBundleId: 'com.example.shopListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHPlil8BnNdxvqY845jPq1KWGrcxAdZrU',
    appId: '1:637551684753:ios:98c24bec247b62a8722330',
    messagingSenderId: '637551684753',
    projectId: 'shoplistapp-6faad',
    storageBucket: 'shoplistapp-6faad.firebasestorage.app',
    iosBundleId: 'com.example.shopListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDORoHNqwllIrLwR4EBsa7AQtf2aEe4QLQ',
    appId: '1:637551684753:web:e74ed29ac9e1f3c8722330',
    messagingSenderId: '637551684753',
    projectId: 'shoplistapp-6faad',
    authDomain: 'shoplistapp-6faad.firebaseapp.com',
    storageBucket: 'shoplistapp-6faad.firebasestorage.app',
    measurementId: 'G-DE4NJ9MH96',
  );
}
