name: Scheduled Scraping

on:
  schedule:
    - cron: '0 8 */3 * *'   # minden 3. napon 8:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: shop_list_app/backend  

    steps:
      - name: Repository klónozása
        uses: actions/checkout@v4

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget chromium-browser
          sudo ln -s /usr/bin/chromium-browser /usr/bin/chrome 
        
      - name: Debug – fájlok listázása
        run: ls -R
        
      - name: Node.js telepítése
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'shop_list_app/backend/package-lock.json'

      - name: Függőségek telepítése
        run: npm ci

      - name: .env létrehozása
        run: |
          echo "FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }}" >> .env
          echo "FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}" >> .env
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
          echo "PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser" >> .env

      - name: TypeScript build
        run: npx tsc

      - name: Scraper futtatása
        run: node dist/index.js scrape
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
